language: elixir
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.5.2
otp_release:
  - 20.1
before_script:
  - MIX_ENV=test mix deps.get
script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - mix test